version: '3.8'

services:
  # --- Service 1 : L'API (Backend) ---
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mon-api-reco
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data  # Astuce : Pour ne pas rebuilder si tu changes le modèle
    networks:
      - mon-reseau

  # --- Service 2 : L'Interface (Frontend) ---
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: mon-ui-reco
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000  # <--- MAGIE : Le frontend parle au backend via son nom
    depends_on:
      - backend  # Attend que l'API soit prête avant de lancer l'UI
    networks:
      - mon-reseau

networks:
  mon-reseau:
    driver: bridge